name: '${project.name}'
version: '${project.version}'
main: org.mcausc78.fimespm.FimesPMPlugin
load: STARTUP
softdepend: [ PlaceholderAPI ]
authors: [ MCausc78 ]
description: A FimesCraft project plugin manager.
commands:
  fpm:
    description: 'Manage plugins'
    usage: '/<command> (Startup error)'
    